### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by grudloff** [conda-forge/cudatoolkit-dev-feedstock#34]
I am currently using the non-dev version on Windows, but I need PTX which seems to be included here. Is there some particular reason/complication for not supporting Windows right now?

**Comment by xmnlab** [comment]
it seems Windows is not supported since the beginning https://github.com/conda-forge/cudatoolkit-dev-feedstock/commit/c4e857426afe1a3e95106e3c610a57868d87cefd#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR16

I don't know the details, but feel free to open a PR adding the support for Windows.

probably the main files you should change would be https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/cudatoolkit-dev-post-install.py and the meta.yaml ... but maybe you would need to change other files as well, but at least these two files should be the main ones.

thanks!

**Comment by nnkwame** [comment]
Hello! We are also interested in windows support for cudatoolkit-dev, hence I have submitted a PR for this. 
I would be very grateful for any feedback. I will also be grateful for any tips on building successfully with the github ci and conda-forge, since I am new to this ci.

I also would like to ask whether it is possible to build and deploy in conda-forge past cuda windows versions (especially cuda 10.1) if this PR is accepted. Thanks in advance!

**Comment by xmnlab** [comment]
> I also would like to ask whether it is possible to build and deploy in conda-forge past cuda windows versions (especially cuda 10.1) if this PR is accepted. Thanks in advance!

@kidfisch I think that would be fine.

when we have https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/42 merged 
the next step would be following these instructions https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#maintaining-several-versions 

let me know if you have any questions! thank you for all the help!

**Comment by allenleetc** [comment]
> I also would like to ask whether it is possible to build and deploy in conda-forge past cuda windows versions (especially cuda 10.1) if this PR is accepted. Thanks in advance!

@nnkwame @xmnlab 
We are also in need of cudatoolkit-dev on windows for older cuda versions (eg 10.x). 
Currently on conda-forge, I only see windows builds of cudatoolkit-dev for cuda 11.x. 
Am I mistaken here? Are there plans to release builds for older cuda versions on win-64?

Thanks, any information appreciated!
Allen

**Comment by xmnlab** [comment]
I just created a new branch here: https://github.com/conda-forge/cudatoolkit-dev-feedstock/tree/10.x

feel free to open a PR to add the recipe for version 10. so you should open the PR to the branch 10.x (not to the main branch)

you can find something useful from the history: https://github.com/conda-forge/cudatoolkit-dev-feedstock/tree/e20bbc739df0e6029b4a78a274da9e76a21e8d15/recipe

thanks!
